### ISSUE TITLE
Remote meeting this week?

### ISSUE THREAD

**Issue by dlfivefifty** [jaamestaay/M2R-Group-29#7]
I’m in Hong Kong and looking at my schedule my availability will be on Tuesday UK time starting sometime 10:10-10:50.

Let me know if you feel like meeting. Alternatively you can schedule an in person meeting with Daniel/Tianyi.

We will meet in person on Friday as planned.

**Comment by Opsimathy** [comment]
It does not seem that we need a meeting at this point, so I think an in-person meeting on Friday is enough.

By the way, we have already started writing up the report, and you can monitor our progress on GitHub/Overleaf if you would like to. I think we will have already finished at least some parts of it by Friday.

We are looking forward to seeing you at the meeting.
